data:extend{
    {
        type = "bool-setting",
        name = "SubtleMapTileColors-use-speed",
        setting_type = "startup",
        order = 100,
        default_value = false,
    },
    {
        type = "string-setting",
        name = "SubtleMapTileColors-basecolor",
        setting_type = "startup",
        order = 200,
        default_value = "#555555",
    },
    {
        type = "string-setting",
        name = "SubtleMapTileColors-mincolor",
        setting_type = "startup",
        order = 201,
        default_value = "#775533",
    },
    {
        type = "string-setting",
        name = "SubtleMapTileColors-maxcolor",
        setting_type = "startup",
        order = 202,
        default_value = "#445566",
    },
    {
        type = "int-setting",
        name = "SubtleMapTileColors-minspeed",
        setting_type = "startup",
        order = 210,
        default_value = 0,
        minimum_value = 0,
        maximum_value = 100,
    },
    {
        type = "int-setting",
        name = "SubtleMapTileColors-maxspeed",
        setting_type = "startup",
        order = 211,
        default_value = 0,
        minimum_value = 0,
    },
    {
        type = "int-setting",
        name = "SubtleMapTileColors-brightness",
        setting_type = "startup",
        order = 300,
        default_value = 100,
        minimum_value = 0,
        maximum_value = 200,
    },
    {
        type = "int-setting",
        name = "SubtleMapTileColors-saturation",
        setting_type = "startup",
        order = 301,
        default_value = 100,
        minimum_value = 0,
        maximum_value = 200,
    },
}
